### ISSUE TITLE
gmail-manager bug

### ISSUE THREAD

**Issue by goromal** [goromal/anixpkgs#324]
```
[andrew@ats:~]$ gmail-manager clean
 15% (151 of 1000) |########                                                   | Elapsed Time: 0:00:22 ETA:   0:02:05<HttpError 400 when requesting https://gmail.googleapis.com/gmail/v1/users/andrew.torgesen%40gmail.com/threads/192e52b2229255ad?alt=json returned "Precondition check failed.". Details: "[{'message': 'Precondition check failed.', 'domain': 'global', 'reason': 'failedPrecondition'}]">
Traceback (most recent call last):
  File "/nix/store/cflc37lk9ma60jvkdpbl56bp047jq4jf-python3.11-gmail_parser-0.0.0/bin/.gmail-manager-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/cflc37lk9ma60jvkdpbl56bp047jq4jf-python3.11-gmail_parser-0.0.0/lib/python3.11/site-packages/gmail_parser/cli.py", line 104, in main
    cli()
  File "/nix/store/4flhri1nwh8n0d8a4bx2yjnyigpz00bg-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/4flhri1nwh8n0d8a4bx2yjnyigpz00bg-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/nix/store/4flhri1nwh8n0d8a4bx2yjnyigpz00bg-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/4flhri1nwh8n0d8a4bx2yjnyigpz00bg-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/4flhri1nwh8n0d8a4bx2yjnyigpz00bg-python3.11-click-8.1.7/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/4flhri1nwh8n0d8a4bx2yjnyigpz00bg-python3.11-click-8.1.7/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/cflc37lk9ma60jvkdpbl56bp047jq4jf-python3.11-gmail_parser-0.0.0/lib/python3.11/site-packages/gmail_parser/cli.py", line 73, in clean
    inbox = ctx.obj["gmail"].Inbox(num_messages)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/cflc37lk9ma60jvkdpbl56bp047jq4jf-python3.11-gmail_parser-0.0.0/lib/python3.11/site-packages/gmail_parser/corpus.py", line 20, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/cflc37lk9ma60jvkdpbl56bp047jq4jf-python3.11-gmail_parser-0.0.0/lib/python3.11/site-packages/gmail_parser/corpus.py", line 110, in Inbox
    thread_msgs_json = thread_json_message['messages']
                       ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'messages'


```

**Comment by goromal** [comment]
Addressed with https://github.com/goromal/anixpkgs/pull/325
